{"data": "Traceback (most recent call last):\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/utils/zlog.py\", line 39, in log_context\n    yield self\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/proj/main/runscript.py\", line 140, in run_loop\n    runner = setup_runner(\n  File \"/home/mb14sola/.local/lib/python3.10/site-packages/jiant/proj/main/runscript.py\", line 92, in setup_runner\n    jiant_model_setup.delegate_load(\nTypeError: delegate_load() got an unexpected keyword argument 'weights_path'\n", "TIMESTAMP": 1684229521.0720456}
