Lmod: loading gcc 8.5.0 
Lmod: loading python 3.9.5 
Lmod: loading cuda 11.6 
Lmod: loading cuDNN 8.3.1 
wandb: Currently logged in as: few_shot (use `wandb login --relogin` to force relogin)
wandb: Appending key for api.wandb.ai to your netrc file: /home/mb14sola/.netrc
wandb: wandb version 0.12.16 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.12.11
wandb: Run data is saved locally in /work/projects/project01762/CyBERT/wandb/run-20220510_133042-27pu1i2m
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run chocolate-shape-271
wandb: ‚≠êÔ∏è View project at https://wandb.ai/few_shot/CyBERT
wandb: üöÄ View run at https://wandb.ai/few_shot/CyBERT/runs/27pu1i2m
404 Client Error: Not Found for url: https://huggingface.co/cybert/model/cybert-ranada/resolve/main/config.json
Traceback (most recent call last):
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/configuration_utils.py", line 550, in get_config_dict
    resolved_config_file = cached_path(
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/file_utils.py", line 1491, in cached_path
    output_path = get_from_cache(
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/file_utils.py", line 1663, in get_from_cache
    r.raise_for_status()
  File "/home/mb14sola/.local/lib/python3.9/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/cybert/model/cybert-ranada/resolve/main/config.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/projects/project01762/CyBERT/cybert/code/MSExchange/run_msexchange_Ranada.py", line 29, in <module>
    tokenizer = AutoTokenizer.from_pretrained(model_name)
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 470, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 558, in from_pretrained
    config_dict, _ = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/mb14sola/.local/lib/python3.9/site-packages/transformers/configuration_utils.py", line 575, in get_config_dict
    raise EnvironmentError(msg)
OSError: Can't load config for 'cybert/model/cybert-ranada'. Make sure that:

- 'cybert/model/cybert-ranada' is a correct model identifier listed on 'https://huggingface.co/models'
  (make sure 'cybert/model/cybert-ranada' is not a path to a local directory with something else, in that case)

- or 'cybert/model/cybert-ranada' is the correct path to a directory containing a config.json file


wandb: Waiting for W&B process to finish... (failed 1). Press Control-C to abort syncing.
wandb: - 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)wandb: \ 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)wandb: | 0.000 MB of 0.004 MB uploaded (0.000 MB deduped)wandb: / 0.000 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: - 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: \ 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: | 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: / 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: - 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: \ 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: | 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: / 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: - 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: \ 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: | 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: / 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb: - 0.006 MB of 0.006 MB uploaded (0.000 MB deduped)wandb:                                                                                
wandb: Synced chocolate-shape-271: https://wandb.ai/few_shot/CyBERT/runs/27pu1i2m
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20220510_133042-27pu1i2m/logs
srun: error: gaqc0001: task 0: Exited with exit code 1
